name: Node.js Publish
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
      env:    
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish  
      run: |
        npm ci
        npm test
        npm run build
        TARGET_VERSION=0.0.0-alpha.$GITHUB_SHA
        echo publish $TARGET_VERSION
        npm version $TARGET_VERSION --git-tag-version=false
        npm publish --tag latest
      env:    
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
